name: sequeler
version: '0.4.1'
summary: Friendly SQL Client
description: |
  Store your Database Connections in the built-in library,
  type and execute SQL commands directly in the App,
  and do everything you need to do without the necessity of opening the terminal.

grade: stable
confinement: strict

icon: sequeler.png

apps:
  sequeler:
    command: desktop-launch sequeler
    plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - gsettings
      - network

parts:
  granite:
    plugin: cmake
    source: lp:granite
    source-type: bzr
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
    build-packages:
      - build-essential
      - valac
    stage-packages:
      - valac-0.30-vapi
  elementary:
    plugin: nil
    prepare: |
      add-apt-repository -y ppa:elementary-os/stable
      add-apt-repository -y ppa:elementary-os/os-patches
      echo "Package: *" > /etc/apt/preferences.d/elementary-stable
      echo "Pin: release o=LP-PPA-elementary-os-stable" >> /etc/apt/preferences.d/elementary-stable
      echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-stable
      echo "Package: *" > /etc/apt/preferences.d/elementary-patches
      echo "Pin: release o=LP-PPA-elementary-os-os-patches" >> /etc/apt/preferences.d/elementary-patches
      echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-patches
      apt update
      apt dist-upgrade -y
  sequeler:
    after: [granite, elementary, desktop-gtk3]
    # source: https://github.com/Alecaddd/sequeler.git
    source: ./
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
    build-packages:
      - build-essential
      - gettext
      - libgee-0.8-dev
      - libgtk-3-dev
      - valac
      - libgranite-dev
      - libjson-glib-dev
      - libgudev-1.0-dev
      - libevdev-dev
      - cmake
      - debhelper
      - libgtksourceview-3.0-dev
      - libxml2-dev
      - libglib2.0-dev
      - libgda-5.0-dev
      - libmysqlclient-dev
      - libpq-dev
      - libgda-5.0-mysql
      - libgda-5.0-postgres
    install: |
      # cp schemas/com.github.alecaddd.sequeler.gschema.xml $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
    prime:
      - usr/share